# git tag
# git tag vx.y.z
# git push --tag

on:
 push:
   tags:
     - v*

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: ""
          - os: windows-latest
            extension: ".exe"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43.6

      - name: Building rokahon on ${{ matrix.os }}
        run: |
          cd rokahon-server
          make compile

      - name: Release ${{ matrix.os }}
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: "rokahon-server/rokahon${{ matrix.extension }}"
          asset_name: "rokahon-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}"
          overwrite: true