name: rokahon tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43.6
      # - name: Verify formatting
      #   run: deno fmt --check
      # - name: Run linter
      #   run: deno lint
      - name: Run rokahon tests
        run: |
          cd rokahon-server
          make test